# Generated by Django 4.2.5 on 2024-03-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districts',
            name='division_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
