# Generated by Django 4.2.11 on 2024-03-21 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_district_forecastdata_forecastmetadata_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecastmetadata',
            options={'verbose_name_plural': 'ForecastMetaData'},
        ),
        migrations.AlterUniqueTogether(
            name='forecastmetadata',
            unique_together={('latitude', 'longitude', 'location_name')},
        ),
    ]
