# Generated by Django 4.2.11 on 2024-03-21 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_forecastmetadata_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='forecastdata',
            unique_together={('forecast_meta_data', 'date')},
        ),
    ]
