# Generated by Django 4.2.11 on 2024-03-20 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_forecastdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecastdata',
            options={'verbose_name_plural': 'ForecastData'},
        ),
    ]
