# Generated by Django 4.2.11 on 2024-03-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_forecastdata_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastmetadata',
            name='location_name',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
